[package]
name = "eisheth"
version = "0.1.0"
edition = "2024"

[dependencies]
llvm-sys = { version = "201.0.1", features = [] }
paste = "1.0.15"
string-interner = "0.19.0"
thiserror = "2.0.12"
eisheth-proc-macros = { path = "../eisheth-proc-macros/" }
expandable = "0.1.1"

[lints]
workspace = true
